export const homeObjOne = {
    id:'about',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Premium Bank',
    headLine:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel:'Get started',
    imgStart:false,
    img:require("../../images/img1.png").default,
    alt:"Car",
    darK:false,
    primary:false,
    darkText:true,
}

export const homeObjTwo = {
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Unlimited access',
    headLine:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel:'Learn more',
    imgStart:true,
    img:require("../../images/img2.png").default,
    alt:"piggy bank",
    darK:false,
    primary:false,
    darkText:true,
}

export const homeObjThree = {
    id:'signup',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Join our team',
    headLine:'Unlimited Transactions with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel:'Learn more',
    imgStart:false,
    img:require("../../images/img3.png").default,
    alt:"paper",
    darK:false,
    primary:false,
    darkText:true,
}